// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqK5dpJjp5vmEarEk1SE9Ucf6A5WuXeJs',
    appId: '1:307635715036:web:c7d6302d213a988af8ed19',
    messagingSenderId: '307635715036',
    projectId: 'invernadero-cisnes',
    authDomain: 'invernadero-cisnes.firebaseapp.com',
    storageBucket: 'invernadero-cisnes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeq21NUNg-9zZ-BH0wQAiIcFnDKh0f29U',
    appId: '1:307635715036:android:c5dbdeaa87c89e6df8ed19',
    messagingSenderId: '307635715036',
    projectId: 'invernadero-cisnes',
    storageBucket: 'invernadero-cisnes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-ENhSkpZ4o_36eKn_EN4YIxoGdps9WU',
    appId: '1:307635715036:ios:e092d6d3a31a3704f8ed19',
    messagingSenderId: '307635715036',
    projectId: 'invernadero-cisnes',
    storageBucket: 'invernadero-cisnes.firebasestorage.app',
    iosBundleId: 'com.example.invernaderoMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-ENhSkpZ4o_36eKn_EN4YIxoGdps9WU',
    appId: '1:307635715036:ios:e092d6d3a31a3704f8ed19',
    messagingSenderId: '307635715036',
    projectId: 'invernadero-cisnes',
    storageBucket: 'invernadero-cisnes.firebasestorage.app',
    iosBundleId: 'com.example.invernaderoMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqnAm7hLePrpXO4FmTQGhiazHo2Q2VhcE',
    appId: '1:307635715036:web:2c763906392bb184f8ed19',
    messagingSenderId: '307635715036',
    projectId: 'invernadero-cisnes',
    authDomain: 'invernadero-cisnes.firebaseapp.com',
    storageBucket: 'invernadero-cisnes.firebasestorage.app',
  );

}